FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
# если есть yarn.lock, то лучше копировать и его
# COPY yarn.lock ./

# ставим yarn (если в образе его ещё нет)
RUN npm install -g yarn

# Установка зависимостей
RUN yarn install    # при необходимости: yarn install --frozen-lockfile

# Сборка
COPY . .
RUN yarn build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/

RUN addgroup -g 1001 -S nginxgroup && \
    adduser -S nginxuser -u 1001 -G nginxgroup

RUN chown -R nginxuser:nginxgroup /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

USER nginxuser

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
