version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=/app/data/users.db
      - SECRET_KEY=${SECRET_KEY}
      - NODE_ENV=production
      - CORS_ORIGIN=http://158.160.148.23:8080  # Обновите порт
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/api
    ports:
      - "8080:80"  # Изменили порт
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local