# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY . .

# Порт
EXPOSE 3000

# Запуск
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
