FROM python:3.11-slim

WORKDIR /app

# Установите системные зависимости + сетевые утилиты
RUN apt-get update && apt-get install -y \
    sqlite3 \
    curl \
    iputils-ping \
    netcat-openbsd \
    dnsutils \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Установка Python зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY . .

# Создаем папку для данных
RUN mkdir -p /app/data

EXPOSE 8000

CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000"]